"""Button -> Elite Dangerous action map for every page button that sends keys.

Keys are NOT stored here: tools/extract_keybinds.py reads them from the .tml pages,
so the docs always show exactly what the buttons send.
Menu = where the action lives in the game's Options > Controls menu (English UI).
"""

# ED internal action name -> (menu section, menu label)
ED_ACTIONS = {
    'LandingGearToggle':        ('Ship Controls › Miscellaneous', 'Landing Gear'),
    'ToggleFlightAssist':       ('Ship Controls › Flight Miscellaneous', 'Toggle Flight Assist'),
    'DeployHardpointToggle':    ('Ship Controls › Weapons', 'Deploy Hardpoints'),
    'ShipSpotLightToggle':      ('Ship Controls › Miscellaneous', 'Ship Lights'),
    'ToggleCargoScoop':         ('Ship Controls › Miscellaneous', 'Cargo Scoop'),
    'NightVisionToggle':        ('Ship Controls › Miscellaneous', 'Night Vision'),
    'DeployHeatSink':           ('Ship Controls › Cooling', 'Deploy Heat Sink'),
    'ToggleButtonUpInput':      ('Ship Controls › Cooling', 'Silent Running'),
    'EjectAllCargo':            ('Ship Controls › Miscellaneous', 'Jettison All Cargo'),
    'TargetNextRouteSystem':    ('Ship Controls › Targeting', 'Target Next System in Route'),
    'FocusLeftPanel':           ('Ship Controls › Mode Switches', 'External Panel (left panel)'),
    'CyclePreviousPanel':       ('General Controls › Interface Mode', 'Previous Panel Tab'),
    'CycleNextPanel':           ('General Controls › Interface Mode', 'Next Panel Tab'),
    'UI_Up':                    ('General Controls › Interface Mode', 'UI Panel Up'),
    'UI_Down':                  ('General Controls › Interface Mode', 'UI Panel Down'),
    'UI_Left':                  ('General Controls › Interface Mode', 'UI Panel Left'),
    'UI_Right':                 ('General Controls › Interface Mode', 'UI Panel Right'),
    'UI_Select':                ('General Controls › Interface Mode', 'UI Panel Select'),
    'CyclePreviousSubsystem':   ('Ship Controls › Targeting', 'Cycle Previous Subsystem'),
    'WingNavLock':              ('Ship Controls › Targeting', 'Wingman Nav-Lock'),
    'OrderRequestDock':         ('Ship Controls › Fighter Orders', 'Recall Fighter'),
    'OrderDefensiveBehaviour':  ('Ship Controls › Fighter Orders', 'Defend'),
    'OrderAggressiveBehaviour': ('Ship Controls › Fighter Orders', 'Engage At Will'),
    'OrderFocusTarget':         ('Ship Controls › Fighter Orders', 'Attack Target'),
    'OrderHoldFire':            ('Ship Controls › Fighter Orders', 'Maintain Formation'),
    'OrderHoldPosition':        ('Ship Controls › Fighter Orders', 'Hold Position'),
    'OrderFollow':              ('Ship Controls › Fighter Orders', 'Follow Me'),
    'ToggleFreeCam':            ('General Controls › Free Camera', 'Toggle Free Camera'),
    'FreeCamZoomIn':            ('General Controls › Free Camera', 'Zoom In'),
    'FreeCamZoomOut':           ('General Controls › Free Camera', 'Zoom Out'),
    'FixCameraWorldToggle':     ('General Controls › Free Camera', 'Lock to World'),
    'RollCameraLeft':           ('General Controls › Free Camera', 'Roll Left'),
    'RollCameraRight':          ('General Controls › Free Camera', 'Roll Right'),
    'MoveFreeCamForward':       ('General Controls › Free Camera', 'Move Forward'),
    'MoveFreeCamBackwards':     ('General Controls › Free Camera', 'Move Backwards'),
    'ToggleAdvanceMode':        ('General Controls › Free Camera', 'Toggle Zoom/Blur (Advanced Mode)'),
    'ToggleRotationLock':       ('General Controls › Free Camera', 'Toggle Rotation Lock (Stabiliser)'),
    'FixCameraRelativeToggle':  ('General Controls › Free Camera', 'Lock to Ship'),
    'PhotoCameraToggle':        ('General Controls › Camera Suite', 'Toggle Camera Suite'),
    'AutoBreakBuggyButton':     ('SRV Controls › Driving', 'Handbrake'),
    'ToggleBuggyTurretButton':  ('SRV Controls › Mode Switches', 'Toggle Turret Mode'),
    'ToggleDriveAssist':        ('SRV Controls › Driving', 'Drive Assist'),
    'HeadlightsBuggyButton':    ('SRV Controls › Miscellaneous', 'Headlights'),
    'BuggyCycleFireGroupNext':  ('SRV Controls › Weapons', 'Next Fire Group'),
    'FocusLeftPanel_Buggy':     ('SRV Controls › Mode Switches', 'External Panel'),
    'FocusCommsPanel_Buggy':    ('SRV Controls › Mode Switches', 'Comms Panel'),
    'FocusRadarPanel_Buggy':    ('SRV Controls › Mode Switches', 'Role Panel'),
    'FocusRightPanel_Buggy':    ('SRV Controls › Mode Switches', 'Internal Panel'),
    'QuickCommsPanel_Buggy':    ('SRV Controls › Mode Switches', 'Quick Comms'),
    'RecallDismissShip':        ('SRV Controls › Miscellaneous', 'Recall / Dismiss Ship'),
}

# (page file, row, col) -> (button label on the tablet, [ED actions in order], note)
BUTTONS = {
    ('ED - Vuelo.tml', 4, 0):   ('LANDING GEAR', ['LandingGearToggle'], ''),
    ('ED - Vuelo.tml', 4, 2):   ('FA OFF', ['ToggleFlightAssist'], ''),
    ('ED - Vuelo.tml', 4, 4):   ('HARDPOINTS', ['DeployHardpointToggle'], ''),
    ('ED - Vuelo.tml', 4, 6):   ('LIGHTS', ['ShipSpotLightToggle'], ''),
    ('ED - Vuelo.tml', 4, 8):   ('CARGO SCOOP', ['ToggleCargoScoop'], ''),
    ('ED - Vuelo.tml', 4, 10):  ('NIGHT VISION', ['NightVisionToggle'], ''),
    ('ED - Vuelo.tml', 7, 0):   ('HEAT SINK', ['DeployHeatSink'], ''),
    ('ED - Vuelo.tml', 7, 3):   ('SILENT RUNNING', ['ToggleButtonUpInput'], ''),
    ('ED - Vuelo.tml', 7, 5):   ('JETTISON ALL CARGO', ['EjectAllCargo'], ''),
    ('ED - Vuelo.tml', 7, 7):   ('TARGET NEXT SYSTEM', ['TargetNextRouteSystem'], ''),
    ('ED - Vuelo.tml', 7, 9):   ('REQUEST DOCKING', ['FocusLeftPanel', 'CyclePreviousPanel', 'CyclePreviousPanel', 'UI_Right', 'UI_Select'], 'macro'),
    ('ED - Combate.tml', 1, 0): ('TARGET POWER PLANT', ['CyclePreviousSubsystem'], 'macro6'),
    ('ED - Combate.tml', 1, 5): ('TEAM MATE NAV LOCK', ['WingNavLock'], ''),
    ('ED - Combate.tml', 1, 7): ('REQUEST DOCKING', ['FocusLeftPanel', 'CyclePreviousPanel', 'CyclePreviousPanel', 'UI_Right', 'UI_Select'], 'macro'),
    ('ED - Combate.tml', 7, 0): ('RECALL FIGHTER', ['OrderRequestDock'], ''),
    ('ED - Combate.tml', 7, 2): ('DEFEND', ['OrderDefensiveBehaviour'], ''),
    ('ED - Combate.tml', 7, 3): ('ENGAGE AT WILL', ['OrderAggressiveBehaviour'], ''),
    ('ED - Combate.tml', 7, 5): ('ATTACK TARGET', ['OrderFocusTarget'], ''),
    ('ED - Combate.tml', 7, 7): ('MAINTAIN FORMATION', ['OrderHoldFire'], ''),
    ('ED - Combate.tml', 7, 9): ('HOLD POSITION', ['OrderHoldPosition'], ''),
    ('ED - Combate.tml', 7, 11): ('FOLLOW ME', ['OrderFollow'], ''),
    ('ED - Cámara.tml', 2, 0):  ('FREE CAMERA ON / OFF', ['ToggleFreeCam'], ''),
    ('ED - Cámara.tml', 2, 6):  ('ZOOM +', ['FreeCamZoomIn'], ''),
    ('ED - Cámara.tml', 2, 8):  ('ZOOM -', ['FreeCamZoomOut'], ''),
    ('ED - Cámara.tml', 2, 10): ('LOCK', ['FixCameraWorldToggle'], ''),
    ('ED - Cámara.tml', 4, 0):  ('ROLL LEFT', ['RollCameraLeft'], ''),
    ('ED - Cámara.tml', 4, 3):  ('ROLL RIGHT', ['RollCameraRight'], ''),
    ('ED - Cámara.tml', 4, 6):  ('MOVE FORWARD', ['MoveFreeCamForward'], ''),
    ('ED - Cámara.tml', 4, 9):  ('MOVE BACK', ['MoveFreeCamBackwards'], ''),
    ('ED - Cámara.tml', 6, 0):  ('ZOOM / BLUR TOGGLE', ['ToggleAdvanceMode'], ''),
    ('ED - Cámara.tml', 6, 4):  ('STABILISER OFF', ['ToggleRotationLock'], ''),
    ('ED - Cámara.tml', 6, 8):  ('SHIP CONTROLS', ['FixCameraRelativeToggle'], ''),
    ('ED - Cámara.tml', 9, 0):  ('PHOTO MODE', ['PhotoCameraToggle'], ''),
    ('ED - SRV.tml', 3, 0):     ('HANDBRAKE', ['AutoBreakBuggyButton'], ''),
    ('ED - SRV.tml', 3, 4):     ('TURRET VIEW', ['ToggleBuggyTurretButton'], ''),
    ('ED - SRV.tml', 5, 0):     ('DRIVE ASSIST', ['ToggleDriveAssist'], ''),
    ('ED - SRV.tml', 5, 6):     ('HIGH BEAMS', ['HeadlightsBuggyButton'], ''),
    ('ED - SRV.tml', 7, 0):     ('NEXT GROUP', ['BuggyCycleFireGroupNext'], ''),
    ('ED - SRV.tml', 7, 2):     ('EXTERNAL PANEL', ['FocusLeftPanel_Buggy'], ''),
    ('ED - SRV.tml', 7, 4):     ('COMMS PANEL', ['FocusCommsPanel_Buggy'], ''),
    ('ED - SRV.tml', 7, 6):     ('ROLE PANEL', ['FocusRadarPanel_Buggy'], ''),
    ('ED - SRV.tml', 7, 8):     ('INTERNAL PANEL', ['FocusRightPanel_Buggy'], ''),
    ('ED - SRV.tml', 7, 10):    ('QUICK COMMS', ['QuickCommsPanel_Buggy'], ''),
    ('ED - SRV.tml', 9, 0):     ('PREVIOUS PAGE', ['CyclePreviousPanel'], ''),
    ('ED - SRV.tml', 9, 2):     ('UP', ['UI_Up'], ''),
    ('ED - SRV.tml', 9, 4):     ('NEXT PAGE', ['CycleNextPanel'], ''),
    ('ED - SRV.tml', 9, 6):     ('RECALL SHIP', ['RecallDismissShip'], ''),
    ('ED - SRV.tml', 11, 0):    ('LEFT', ['UI_Left'], ''),
    ('ED - SRV.tml', 11, 2):    ('DOWN', ['UI_Down'], ''),
    ('ED - SRV.tml', 11, 4):    ('RIGHT', ['UI_Right'], ''),
}

PAGE_TAB = {'ED - Vuelo.tml': 'FLIGHT', 'ED - Combate.tml': 'COMBAT', 'ED - Cámara.tml': 'CAMERA', 'ED - SRV.tml': 'SRV'}
